### ISSUE TITLE
Form changes

### ISSUE THREAD

**Issue by AndreasSchantl** [studio1902/statamic-peak#369]
There's a few things I always tend to change when dealing with forms in Peak.

## Checking against the visibility in email templates
Instead of the hardcoded check against the ``consent`` like this ``{{ if value && handle !== 'consent' }}`` I rather tend to do this: ``{{ if value && {config['visibility']} != 'hidden' }}``.

## Showing the label for selects if set
``{{ value:label or value }}`` instead of just ``{{ value }}``

## Setting the whitespace to normal to prevent additional unwanted lines in emails
``<pre style="white-space:normal;"``, currently it is set to ``pre-line``

**Comment by robdekort** [comment]
Hey Andreas! 

Thank you. Lovely feedback. Diving in.

**Visibility in email templates**
After checking the blueprint builder I see the visiblity things acutally hides it from _publish_ forms. So I think it's a great idea to use this instead of the `{{ if }}`. Good call! 

_Note_: We should also update the docs regarding the `consent` handle: https://peak.1902.studio/features/forms.html#forms

**Showing the label for selects if set**
Nice. In the email I guess? Perhaps it should be `{{ value:label ?? value }}`. 

**Whitespace**
Not sure why it's even in there. Let's kick it out!
