### ISSUE TITLE
TW breakpoint indicator breaks when extending screen sizes

### ISSUE THREAD

**Issue by robdekort** [studio1902/statamic-peak#98]
**Describe the bug**
after adding xs: '375px',  via extend in site config everything above xs is indicated as xs. Utility generation is not affected
It works if I override the entire screens objecft instead of extending it though, that works for me for now, too.

Note to self: probably order the breakpoints first

**Comment by sjclark** [comment]
pssst....
```
  plugins: [
    require('tailwindcss-debug-screens')
  ],
    theme: {
    debugScreens: {
      position: ['top', 'right'],
    },
  },
  ```

**Comment by robdekort** [comment]
@sjclark that one doesn't sort either :-)

**Comment by sjclark** [comment]
Ahhhh….
```
If you want to add an additional small breakpoint, you can't use extend because the small breakpoint would be added to the end of the breakpoint list, and breakpoints need to be sorted from smallest to largest in order to work as expected with a min-width breakpoint system.
Instead, override the entire screens key, re-specifying the default breakpoints:
```

**Comment by sjclark** [comment]
Ahhhh….

If you want to add an additional small breakpoint, you can't use extend because the small breakpoint would be added to the end of the breakpoint list, and breakpoints need to be sorted from smallest to largest in order to work as expected with a min-width breakpoint system.
Instead, override the entire screens key, re-specifying the default breakpoints:

![Screen Shot 2021-04-23 at 5 36 27 pm](https://user-images.githubusercontent.com/4531017/115836130-76148400-a45a-11eb-87f1-34bc98cc82fb.png)

**Comment by robdekort** [comment]
But what if you want to add one in the middle?

**Comment by robdekort** [comment]
I can probably sort the thing, just have to make sure to take out all other 'breakpoints' people may have, like dark mode, print css, or orientation stuff.

**Comment by sjclark** [comment]
> But what if you want to add one in the middle?

Nah, not allowed, Tailwind self-implodes and deletes your project.

But yea, does seem fiddly, think you're right about probably having to order things.

**Comment by robdekort** [comment]
Just pushed a commit that fixes this. Wanna give it a go @klickreflex?

My JS skills suck, so feel free to PR nicer code.
